# Dockerfile

FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev build-essential git \
    libglib2.0-0 libsm6 libxext6 libxrender-dev libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

# create the symlinks YOLOv5 needs:
RUN ln -s /app/data/train/annotations /app/data/train/labels && \
    ln -s /app/data/val/annotations   /app/data/val/labels   && \
    ln -s /app/data/test/annotations  /app/data/test/labels

RUN pip3 install --upgrade pip && \
    pip3 install \
      networkx==2.8.8 \
      torch torchvision --extra-index-url https://download.pytorch.org/whl/cu117 \
      opencv-python-headless numpy onnxruntime flask pillow matplotlib \
      ultralytics

EXPOSE 5000

CMD ["python3", "src/deploy/server.py"]
